### ISSUE TITLE
A infinite ammo shotgun

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#8] opened 2021-05-03 15:06 UTC
This occurred when assaulting officers near the station and airport resulting in them dropping weapons, one of which was a shotgun that had infinite ammo.

-YaDad

**Comment by Jamie-D-T** [comment] 2021-05-03 22:29
Duplicate 
Duplicate of #7

**Closed** 2021-05-17 16:43 UTC
Labels: Code removed, Duplicate
