### ISSUE TITLE
Server Description

### ISSUE THREAD

**Issue by thefireman504** [2nd-alarm/FiveM#48] opened 2021-05-29 14:12 UTC
![image](https://user-images.githubusercontent.com/62909235/120073444-f0d64d80-c05d-11eb-9e3a-1d842ce0738c.png)
![image](https://user-images.githubusercontent.com/62909235/120073456-ff246980-c05d-11eb-8add-f55c16a7f289.png)
might want to change these....

**Comment by ZackDallaire112** [comment] 2021-05-29 16:12
This is a Duplicate of[ this ticket](https://github.com/2nd-alarm/FiveM/issues/47)

**Closed by ZackDallaire112** 2021-05-29 16:12 UTC
Labels: Bug, Duplicate
