### ISSUE TITLE
[BUG] SATD police garage spawns you in the car you choose, but it drops you at mission row PD

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#111] opened 2021-12-03 01:06 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Jamie-D-T** [comment] 2021-12-14 04:31
Duplicate of #106

**Closed by Jamie-D-T** 2021-12-14 04:31 UTC
Labels: Bug, Active Solution In Progress
